### ISSUE TITLE
Remove home-manager from flake input

### ISSUE THREAD

**Issue by juuyokka** [Juiced-Devs/Kalyx#3]
The `home-manager` flake input may be entirely unnecessary, and removing it would simplify usage and would make `home-manager` optional for users who don't use it. The end user would be able to write this in their flake
```nix
inputs.kalyx = {
  url = "github:...";
  inputs.nixpkgs.follows = "nixpkgs";
};
```
as opposed to what we do currently
```nix
inputs.kalyx = {
  url = "github:...";
  inputs.nixpkgs.follows = "nixpkgs";
  inputs.home-manager.follows = "home-manager";
};
```
More testing needs to be done if this is even possible.

**Comment by kyleraykbs** [comment]
Not a bad idea, the only problem I have with that is that a few of our modules currently, notably NVIDIA and XDG Portals edit home manager functionality from NixOS scope and would need an if check.

**Comment by kyleraykbs** [comment]
Good idea, done.
