### ISSUE TITLE
Steam hyprland fix (seemingly) causes hyprland to freeze/crash

### ISSUE THREAD

**Issue by SkettiSouls** [Juiced-Devs/Kalyx#6]
After a few weeks of using the steam module, I noticed I was having frequent issues were hyprland would permanently freeze, locking me out of using the keyboard or clicking, but still moving my mouse, which was only fixable by a hard reboot. Eventually I decided to try disabling this bit here and haven't had any issues in the roughly 10 days since.

    home-manager.sharedModules = [{
      
      # Hyprland steam dropdown menu fix.
      wayland.windowManager.hyprland.settings = {
        windowrulev2 = [
          "stayfocused, title:^()$,class:^(steam)$"
          "minsize 1 1, title:^()$,class:^(steam)$"
        ];
      };
    }];

**Comment by kyleraykbs** [comment]
Needs further testing.

**Comment by SkettiSouls** [comment]
Definitely the cause as I haven't had the issue in months since removing the aforementioned code.
Additionally the issue that the fix is addressing no longer occurs in nixpkgs 24.05.
